# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\MI\Desktop\ZJUDancer-测试软件\ZJUDancer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1215, 919)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.TotalInterface = QtWidgets.QVBoxLayout()
        self.TotalInterface.setObjectName("TotalInterface")
        self.MainInterface = QtWidgets.QHBoxLayout()
        self.MainInterface.setObjectName("MainInterface")
        self.GB_Serial = QtWidgets.QGroupBox(self.centralwidget)
        self.GB_Serial.setObjectName("GB_Serial")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.GB_Serial)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.SerialControl = QtWidgets.QHBoxLayout()
        self.SerialControl.setObjectName("SerialControl")
        self.CB_SerialList = QtWidgets.QComboBox(self.GB_Serial)
        self.CB_SerialList.setObjectName("CB_SerialList")
        self.SerialControl.addWidget(self.CB_SerialList)
        self.PB_FreshList = QtWidgets.QPushButton(self.GB_Serial)
        self.PB_FreshList.setObjectName("PB_FreshList")
        self.SerialControl.addWidget(self.PB_FreshList)
        self.PB_OpenSerial = QtWidgets.QPushButton(self.GB_Serial)
        self.PB_OpenSerial.setObjectName("PB_OpenSerial")
        self.SerialControl.addWidget(self.PB_OpenSerial)
        self.PB_CloseSerial = QtWidgets.QPushButton(self.GB_Serial)
        self.PB_CloseSerial.setObjectName("PB_CloseSerial")
        self.SerialControl.addWidget(self.PB_CloseSerial)
        self.PB_ClearLog = QtWidgets.QPushButton(self.GB_Serial)
        self.PB_ClearLog.setObjectName("PB_ClearLog")
        self.SerialControl.addWidget(self.PB_ClearLog)
        self.PB_SwitchLog = QtWidgets.QPushButton(self.GB_Serial)
        self.PB_SwitchLog.setObjectName("PB_SwitchLog")
        self.SerialControl.addWidget(self.PB_SwitchLog)
        self.SerialControl.setStretch(0, 1)
        self.SerialControl.setStretch(1, 1)
        self.SerialControl.setStretch(2, 1)
        self.SerialControl.setStretch(3, 1)
        self.verticalLayout.addLayout(self.SerialControl)
        self.SerialLog = QtWidgets.QTextEdit(self.GB_Serial)
        self.SerialLog.setObjectName("SerialLog")
        self.verticalLayout.addWidget(self.SerialLog)
        self.LB_Speed = QtWidgets.QLabel(self.GB_Serial)
        self.LB_Speed.setObjectName("LB_Speed")
        self.verticalLayout.addWidget(self.LB_Speed)
        self.LB_Pos = QtWidgets.QLabel(self.GB_Serial)
        self.LB_Pos.setObjectName("LB_Pos")
        self.verticalLayout.addWidget(self.LB_Pos)
        self.LB_ADIS = QtWidgets.QLabel(self.GB_Serial)
        self.LB_ADIS.setObjectName("LB_ADIS")
        self.verticalLayout.addWidget(self.LB_ADIS)
        self.LB_FootData = QtWidgets.QLabel(self.GB_Serial)
        self.LB_FootData.setObjectName("LB_FootData")
        self.verticalLayout.addWidget(self.LB_FootData)
        self.LB_RevRaw = QtWidgets.QLabel(self.GB_Serial)
        self.LB_RevRaw.setObjectName("LB_RevRaw")
        self.verticalLayout.addWidget(self.LB_RevRaw)
        self.LB_SendBuffer = QtWidgets.QLabel(self.GB_Serial)
        self.LB_SendBuffer.setObjectName("LB_SendBuffer")
        self.verticalLayout.addWidget(self.LB_SendBuffer)
        self.GB_CTRL = QtWidgets.QHBoxLayout()
        self.GB_CTRL.setObjectName("GB_CTRL")
        self.FootData_CTRL = QtWidgets.QCheckBox(self.GB_Serial)
        self.FootData_CTRL.setChecked(True)
        self.FootData_CTRL.setObjectName("FootData_CTRL")
        self.GB_CTRL.addWidget(self.FootData_CTRL)
        self.SendData_CTRL = QtWidgets.QCheckBox(self.GB_Serial)
        self.SendData_CTRL.setChecked(True)
        self.SendData_CTRL.setObjectName("SendData_CTRL")
        self.GB_CTRL.addWidget(self.SendData_CTRL)
        self.verticalLayout.addLayout(self.GB_CTRL)
        self.horizontalLayout_15.addLayout(self.verticalLayout)
        self.MainInterface.addWidget(self.GB_Serial)
        self.MainInterface.setStretch(0, 6)
        self.TotalInterface.addLayout(self.MainInterface)
        self.verticalLayout_3.addLayout(self.TotalInterface)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GB_Serial.setTitle(_translate("MainWindow", "串口操作"))
        self.PB_FreshList.setText(_translate("MainWindow", "刷新列表"))
        self.PB_OpenSerial.setText(_translate("MainWindow", "打开串口"))
        self.PB_CloseSerial.setText(_translate("MainWindow", "关闭串口"))
        self.PB_ClearLog.setText(_translate("MainWindow", "清空窗口"))
        self.PB_SwitchLog.setText(_translate("MainWindow", "暂停显示"))
        self.LB_Speed.setText(_translate("MainWindow", "位置:"))
        self.LB_Pos.setText(_translate("MainWindow", "速度:"))
        self.LB_ADIS.setText(_translate("MainWindow", "陀螺仪数据:"))
        self.LB_FootData.setText(_translate("MainWindow", "足底板数据"))
        self.LB_RevRaw.setText(_translate("MainWindow", "原始数据:"))
        self.LB_SendBuffer.setText(_translate("MainWindow", "发送数据:"))
        self.FootData_CTRL.setText(_translate("MainWindow", "压力板开启"))
        self.SendData_CTRL.setText(_translate("MainWindow", "数据发送"))

